apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devtools-applicationset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/netanelzucaim/devtools-provision.git
    targetRevision: main
    path: .
    directory:
      include: applicationset.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
