apiVersion: v2
name: woodpecker
description: Woodpecker CI - A simple CI engine with great extensibility
type: application
version: 1.0.0
appVersion: "v2.7.0"

dependencies:
  - name: woodpecker
    version: "0.1.0"
    repository: "file://../charts/woodpecker"
