apiVersion: v2
name: argocd
description: Argo CD - Declarative GitOps CD for Kubernetes
type: application
version: 1.0.0
appVersion: "v2.13.0"

dependencies:
  - name: argo-cd
    version: 7.7.5
    repository: https://argoproj.github.io/argo-helm
