apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-server
  labels:
    app: {{ .Chart.Name }}-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.httpPort }}
      targetPort: 8000
      protocol: TCP
      name: http
    - port: {{ .Values.server.service.grpcPort }}
      targetPort: 9000
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Chart.Name }}-server
