apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gitea.service.http.type }}
  ports:
  - port: {{ .Values.gitea.service.http.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gitea.service.ssh.type }}
  ports:
  - port: {{ .Values.gitea.service.ssh.port }}
    targetPort: ssh
    protocol: TCP
    name: ssh
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
